name: Non-Production workflow
on:
  workflow_dispatch:
  push:
    branches:
      - 'main' 
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      # - '.github/workflows/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/yourusername/your-repo-name
      DEPLOY_ENV: nonprd
      PORT: 8080
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=edge
            type=sha,prefix=${{ env.DEPLOY_ENV }}-,priority=750

      # print tag info
      - name: Print tag info
        run: |
          echo "Image Name: ${{ env.IMAGE_NAME }}"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"




